/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package datascience;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pessoal
 */
public class FrmEntidadeSA extends javax.swing.JDialog {

    private java.awt.Frame parent;

    public Controle controle;
    public Entidade entidadeSelecionadaSA;
    public Entidade entidadeAtualSA;
    public Atributo atributoSelecionado;
    public MapeamentoSA mapeamentoSelecionado;

    /**
     * Creates new form FrmDimensaoFato
     */
    public FrmEntidadeSA(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        this.parent = parent;

        //desativando controles
        btnNovo.setEnabled(false);
        btnSalvar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnAtributo.setEnabled(false);
        btnFechar.setEnabled(true);

        this.atributoSelecionado = null;

    }

    public void AtualizarConexao() {

        DefaultComboBoxModel model = new DefaultComboBoxModel();
        if (controle != null) {
            if (controle.getConexoes() != null) {
                for (Conexao conexao : controle.getConexoes()) {
                    if (conexao.getObjetivo().equals("Staging Area")) {
                        model.addElement(conexao);
                    }
                }
            }
        }
        cbxConexão.setModel(model);
    }

    private void CarregaAtributos() {

        DefaultTableModel modelAtributo = (DefaultTableModel) this.tblAtributos.getModel();
        tblAtributos.getColumnModel().getColumn(4).setWidth(0);
        tblAtributos.getColumnModel().getColumn(4).setMinWidth(0);
        tblAtributos.getColumnModel().getColumn(4).setMaxWidth(0);

        //ativando controles
        btnAtributo.setEnabled(false);
        if (this.entidadeAtualSA.getAtributos().size() > 0) {
            modelAtributo.setRowCount(0);
            for (Atributo atributo : this.entidadeAtualSA.getAtributos()) {
                modelAtributo.setRowCount(modelAtributo.getRowCount() + 1);
                modelAtributo.setValueAt(atributo.getNome(), modelAtributo.getRowCount() - 1, 0);
                modelAtributo.setValueAt(atributo.getTipo(), modelAtributo.getRowCount() - 1, 1);
                modelAtributo.setValueAt(atributo.getTamanho(), modelAtributo.getRowCount() - 1, 2);
                modelAtributo.setValueAt(atributo.getPrecisao(), modelAtributo.getRowCount() - 1, 3);
                modelAtributo.setValueAt(atributo, modelAtributo.getRowCount() - 1, 4);
            }
            tblAtributos.setModel(modelAtributo);
            btnAtributo.setEnabled(true);
        }
    }

    public void LimparTela() {

        this.entidadeSelecionadaSA = null;
        //crinando um novo objeto
        this.entidadeAtualSA = new Entidade();

        AtualizarConexao();
        cbxConexão.setSelectedIndex(-1);

        txtNome.setText("");
        txtDescricao.setText("");

        CarregaAtributos();

        //ativando controles
        btnNovo.setEnabled(false);
        btnSalvar.setEnabled(true);
        btnExcluir.setEnabled(false);

    }

    public void AtualizaAtual() {

        Object[] model = cbxConexão.getSelectedObjects();
        if (model.length > 0) {
            Conexao conexao = (Conexao) model[0];
            this.entidadeAtualSA.setConexao(conexao);
        }

        this.entidadeAtualSA.setNome(txtNome.getText());
        this.entidadeAtualSA.setDescricao(txtDescricao.getText());

    }

    public void SetEntidadeSelecionada(Entidade entidade) {

        this.entidadeSelecionadaSA = entidade;
        this.entidadeAtualSA = entidade.copia();

        AtualizarConexao();

        if (this.entidadeAtualSA != null) {

            cbxConexão.setSelectedItem(entidadeAtualSA.getConexao());
            txtNome.setText(entidadeAtualSA.getNome());
            txtDescricao.setText(entidadeAtualSA.getDescricao());
            CarregaAtributos();

            //ativando controles
            btnNovo.setEnabled(true);
            btnSalvar.setEnabled(true);
            btnExcluir.setEnabled(true);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        btnFechar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnAtributo = new javax.swing.JButton();
        btnGerarEntidadeDW = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txtNome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescricao = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        cbxConexão = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAtributos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestão de Dimensões e Fatos");

        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnAtributo.setText("Atributo");
        btnAtributo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtributoActionPerformed(evt);
            }
        });

        btnGerarEntidadeDW.setText("Gerar destino em DW");
        btnGerarEntidadeDW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarEntidadeDWActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGerarEntidadeDW)
                .addGap(18, 18, 18)
                .addComponent(btnAtributo)
                .addGap(46, 46, 46)
                .addComponent(btnExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNovo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFechar)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFechar)
                    .addComponent(btnSalvar)
                    .addComponent(btnNovo)
                    .addComponent(btnExcluir)
                    .addComponent(btnAtributo)
                    .addComponent(btnGerarEntidadeDW))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setText("Nome:");

        jLabel2.setText("Descrição:");

        txtDescricao.setColumns(20);
        txtDescricao.setRows(5);
        jScrollPane1.setViewportView(txtDescricao);

        jLabel9.setText("Conexão:");

        jLabel4.setText("Atributos:");

        tblAtributos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Tipo", "Tamanho", "Precisão", "Objeto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAtributos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAtributosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblAtributos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel1))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNome)
                            .addComponent(cbxConexão, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cbxConexão, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed

        dispose();

    }//GEN-LAST:event_btnFecharActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed

        this.AtualizaAtual();
        controle.AddEntidadeSA(this.entidadeSelecionadaSA, this.entidadeAtualSA);

        JOptionPane.showMessageDialog(this, "Entidade salva com sucesso.");
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        LimparTela();
        this.entidadeAtualSA.AddAtributosSA();
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed

        if (this.entidadeSelecionadaSA != null) {
            this.controle.getEntidadesSA().remove(this.entidadeSelecionadaSA);
            controle.getMapeamentosSA().remove(this.mapeamentoSelecionado);
            this.entidadeSelecionadaSA = null;
            dispose();
        }

    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnAtributoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtributoActionPerformed

        if (this.atributoSelecionado != null) {
            FrmAtributo frmAtributo = new FrmAtributo(this.parent, true);
            frmAtributo.controle = this.controle;
            frmAtributo.entidadeSelecionada = this.entidadeAtualSA;
            frmAtributo.LimparTela();
            frmAtributo.SetAtributoSelecionado(this.atributoSelecionado, "SA");
            frmAtributo.pack();
            frmAtributo.setLocationRelativeTo(null);
            frmAtributo.setVisible(true);
            CarregaAtributos();
        }
    }//GEN-LAST:event_btnAtributoActionPerformed

    private void tblAtributosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAtributosMouseClicked
        // TODO add your handling code here:
        Atributo tempAtributo = new Atributo();
        if (tblAtributos.getSelectedRow() >= 0) {
            for (Atributo atributo : this.entidadeAtualSA.getAtributos()) {
                if (atributo.equals((Atributo) tblAtributos.getValueAt(tblAtributos.getSelectedRow(), 4))) {
                    tempAtributo = atributo;
                }
            }
        }
        if (this.atributoSelecionado != null) {
            if (this.atributoSelecionado.equals(tempAtributo)) {
                btnAtributoActionPerformed(null);
            } else {
                this.atributoSelecionado = tempAtributo;
            }
        } else {
            this.atributoSelecionado = tempAtributo;
        }
    }//GEN-LAST:event_tblAtributosMouseClicked

    private void btnGerarEntidadeDWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarEntidadeDWActionPerformed
        // TODO add your handling code here:
        AtualizaAtual();
        if (this.entidadeSelecionadaSA.equals(this.entidadeAtualSA)) {

            MapeamentoDW mapeamentoDW = null;
            for (MapeamentoDW mapa : this.controle.getMapeamentosDW()) {
                if (mapa.getEntidadeSAOrigem().equals(this.entidadeSelecionadaSA)) {
                    mapeamentoDW = mapa;
                }
            }

            if (mapeamentoDW == null) {

                Entidade novaEntidade = new Entidade();
                novaEntidade = this.entidadeSelecionadaSA.copia();
                novaEntidade.setNome("FATO_DIM_"+novaEntidade.getNome());
                this.controle.AddEntidadeDW(null, novaEntidade);

                mapeamentoDW = new MapeamentoDW();
                mapeamentoDW.setEntidadeSAOrigem(this.entidadeSelecionadaSA);
                mapeamentoDW.setEntidadeDWDestino(novaEntidade);
                this.controle.AddMapeamentoDW(null, mapeamentoDW);

                JOptionPane.showMessageDialog(this, "Entidade copiada para Data Warehouse.");
            }

            FrmEntidadeDW frmEntidadeDW = new FrmEntidadeDW(this.parent, true);
            frmEntidadeDW.controle = this.controle;
            frmEntidadeDW.mapeamentoSelecionado = mapeamentoDW;
            frmEntidadeDW.LimparTela();
            frmEntidadeDW.SetEntidadeSelecionada(mapeamentoDW.getEntidadeDWDestino());
            frmEntidadeDW.pack();
            frmEntidadeDW.setLocationRelativeTo(null);
            frmEntidadeDW.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Salve a consulta antes de acessar o mapeamento para Data Warehouse.");
        }
    }//GEN-LAST:event_btnGerarEntidadeDWActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEntidadeSA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEntidadeSA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEntidadeSA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEntidadeSA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmEntidadeSA dialog = new FrmEntidadeSA(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtributo;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnGerarEntidadeDW;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cbxConexão;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tblAtributos;
    private javax.swing.JTextArea txtDescricao;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
